#!/usr/bin/env python3
"""Write src/tables.rs: the characters for bytes 0x80-0xFF in cp1252 and cp850.

The characters come from Python's codecs, which are built from the Unicode
consortium's mapping files. A byte the code page leaves undefined becomes None.
Output is deterministic: running this again leaves git clean.
"""

from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "src" / "tables.rs"

CODE_PAGES = ["cp1252", "cp850"]


def entry(codec, byte):
    try:
        char = bytes([byte]).decode(codec)
    except UnicodeDecodeError:
        return "None"
    return f"Some('\\u{{{ord(char):04X}}}')"


def table(codec):
    rows = []
    for first in range(0x80, 0x100, 8):
        cells = "".join(f"{entry(codec, b) + ',':<18}" for b in range(first, first + 8))
        rows.append(f"    {cells}// 0x{first:02X}")
    body = "\n".join(rows)
    return (
        "#[rustfmt::skip]\n"
        f"pub(crate) static {codec.upper()}: [Option<char>; 128] = [\n{body}\n];\n"
    )


def main():
    header = (
        "// @generated by scripts/gen_tables.py from Python's codecs. Do not edit.\n"
        "//\n"
        "// Each table holds the characters for bytes 0x80..=0xFF (bytes below 0x80\n"
        "// are ASCII). `None` marks a byte the code page leaves undefined.\n"
    )
    tables = "\n".join(table(codec) for codec in CODE_PAGES)
    OUT.write_text(f"{header}\n{tables}", encoding="utf-8")


if __name__ == "__main__":
    main()
