#!/usr/bin/env python3
"""Regenerate src/tables.rs, the single-byte codepage decode tables.

    python3 scripts/gen_tables.py

Each table maps a byte to the character it decodes to, which is well defined for
every single-byte encoding: one byte in, one character out, all 256 of them.
Python's own codecs are the reference, so nothing here is transcribed by hand.

cp1252 leaves five bytes undefined (0x81, 0x8D, 0x8F, 0x90, 0x9D). They are mapped
to the C1 control character of the same value, which is what the WHATWG Encoding
Standard specifies and what other decoders in this space do.
"""

import pathlib

CODECS = [("CP1252", "cp1252"), ("CP850", "cp850"), ("LATIN1", "latin-1")]
OUT = pathlib.Path(__file__).resolve().parent.parent / "src" / "tables.rs"


def decode(codec: str, byte: int) -> str:
    try:
        return bytes([byte]).decode(codec)
    except UnicodeDecodeError:
        return chr(byte)


def table(name: str, codec: str) -> str:
    rows = []
    for base in range(0, 256, 8):
        cells = "".join(f"'\\u{{{ord(decode(codec, b)):04x}}}', " for b in range(base, base + 8))
        rows.append(f"    {cells.rstrip()}")
    body = "\n".join(rows)
    return f"/// `{codec}` decoded byte by byte.\npub static {name}: [char; 256] = [\n{body}\n];\n"


def main() -> None:
    parts = [
        "// @generated by scripts/gen_tables.py -- do not edit by hand.\n",
        "// Regenerate with: python3 scripts/gen_tables.py\n\n",
    ]
    parts.extend(table(name, codec) + "\n" for name, codec in CODECS)
    OUT.write_text("".join(parts).rstrip() + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
