// @generated by scripts/gen_tables.py from Python's codecs. Do not edit.
//
// Each table holds the characters for bytes 0x80..=0xFF (bytes below 0x80
// are ASCII). `None` marks a byte the code page leaves undefined.

#[rustfmt::skip]
pub(crate) static CP1252: [Option<char>; 128] = [
    Some('\u{20AC}'), None,             Some('\u{201A}'), Some('\u{0192}'), Some('\u{201E}'), Some('\u{2026}'), Some('\u{2020}'), Some('\u{2021}'), // 0x80
    Some('\u{02C6}'), Some('\u{2030}'), Some('\u{0160}'), Some('\u{2039}'), Some('\u{0152}'), None,             Some('\u{017D}'), None,             // 0x88
    None,             Some('\u{2018}'), Some('\u{2019}'), Some('\u{201C}'), Some('\u{201D}'), Some('\u{2022}'), Some('\u{2013}'), Some('\u{2014}'), // 0x90
    Some('\u{02DC}'), Some('\u{2122}'), Some('\u{0161}'), Some('\u{203A}'), Some('\u{0153}'), None,             Some('\u{017E}'), Some('\u{0178}'), // 0x98
    Some('\u{00A0}'), Some('\u{00A1}'), Some('\u{00A2}'), Some('\u{00A3}'), Some('\u{00A4}'), Some('\u{00A5}'), Some('\u{00A6}'), Some('\u{00A7}'), // 0xA0
    Some('\u{00A8}'), Some('\u{00A9}'), Some('\u{00AA}'), Some('\u{00AB}'), Some('\u{00AC}'), Some('\u{00AD}'), Some('\u{00AE}'), Some('\u{00AF}'), // 0xA8
    Some('\u{00B0}'), Some('\u{00B1}'), Some('\u{00B2}'), Some('\u{00B3}'), Some('\u{00B4}'), Some('\u{00B5}'), Some('\u{00B6}'), Some('\u{00B7}'), // 0xB0
    Some('\u{00B8}'), Some('\u{00B9}'), Some('\u{00BA}'), Some('\u{00BB}'), Some('\u{00BC}'), Some('\u{00BD}'), Some('\u{00BE}'), Some('\u{00BF}'), // 0xB8
    Some('\u{00C0}'), Some('\u{00C1}'), Some('\u{00C2}'), Some('\u{00C3}'), Some('\u{00C4}'), Some('\u{00C5}'), Some('\u{00C6}'), Some('\u{00C7}'), // 0xC0
    Some('\u{00C8}'), Some('\u{00C9}'), Some('\u{00CA}'), Some('\u{00CB}'), Some('\u{00CC}'), Some('\u{00CD}'), Some('\u{00CE}'), Some('\u{00CF}'), // 0xC8
    Some('\u{00D0}'), Some('\u{00D1}'), Some('\u{00D2}'), Some('\u{00D3}'), Some('\u{00D4}'), Some('\u{00D5}'), Some('\u{00D6}'), Some('\u{00D7}'), // 0xD0
    Some('\u{00D8}'), Some('\u{00D9}'), Some('\u{00DA}'), Some('\u{00DB}'), Some('\u{00DC}'), Some('\u{00DD}'), Some('\u{00DE}'), Some('\u{00DF}'), // 0xD8
    Some('\u{00E0}'), Some('\u{00E1}'), Some('\u{00E2}'), Some('\u{00E3}'), Some('\u{00E4}'), Some('\u{00E5}'), Some('\u{00E6}'), Some('\u{00E7}'), // 0xE0
    Some('\u{00E8}'), Some('\u{00E9}'), Some('\u{00EA}'), Some('\u{00EB}'), Some('\u{00EC}'), Some('\u{00ED}'), Some('\u{00EE}'), Some('\u{00EF}'), // 0xE8
    Some('\u{00F0}'), Some('\u{00F1}'), Some('\u{00F2}'), Some('\u{00F3}'), Some('\u{00F4}'), Some('\u{00F5}'), Some('\u{00F6}'), Some('\u{00F7}'), // 0xF0
    Some('\u{00F8}'), Some('\u{00F9}'), Some('\u{00FA}'), Some('\u{00FB}'), Some('\u{00FC}'), Some('\u{00FD}'), Some('\u{00FE}'), Some('\u{00FF}'), // 0xF8
];

#[rustfmt::skip]
pub(crate) static CP850: [Option<char>; 128] = [
    Some('\u{00C7}'), Some('\u{00FC}'), Some('\u{00E9}'), Some('\u{00E2}'), Some('\u{00E4}'), Some('\u{00E0}'), Some('\u{00E5}'), Some('\u{00E7}'), // 0x80
    Some('\u{00EA}'), Some('\u{00EB}'), Some('\u{00E8}'), Some('\u{00EF}'), Some('\u{00EE}'), Some('\u{00EC}'), Some('\u{00C4}'), Some('\u{00C5}'), // 0x88
    Some('\u{00C9}'), Some('\u{00E6}'), Some('\u{00C6}'), Some('\u{00F4}'), Some('\u{00F6}'), Some('\u{00F2}'), Some('\u{00FB}'), Some('\u{00F9}'), // 0x90
    Some('\u{00FF}'), Some('\u{00D6}'), Some('\u{00DC}'), Some('\u{00F8}'), Some('\u{00A3}'), Some('\u{00D8}'), Some('\u{00D7}'), Some('\u{0192}'), // 0x98
    Some('\u{00E1}'), Some('\u{00ED}'), Some('\u{00F3}'), Some('\u{00FA}'), Some('\u{00F1}'), Some('\u{00D1}'), Some('\u{00AA}'), Some('\u{00BA}'), // 0xA0
    Some('\u{00BF}'), Some('\u{00AE}'), Some('\u{00AC}'), Some('\u{00BD}'), Some('\u{00BC}'), Some('\u{00A1}'), Some('\u{00AB}'), Some('\u{00BB}'), // 0xA8
    Some('\u{2591}'), Some('\u{2592}'), Some('\u{2593}'), Some('\u{2502}'), Some('\u{2524}'), Some('\u{00C1}'), Some('\u{00C2}'), Some('\u{00C0}'), // 0xB0
    Some('\u{00A9}'), Some('\u{2563}'), Some('\u{2551}'), Some('\u{2557}'), Some('\u{255D}'), Some('\u{00A2}'), Some('\u{00A5}'), Some('\u{2510}'), // 0xB8
    Some('\u{2514}'), Some('\u{2534}'), Some('\u{252C}'), Some('\u{251C}'), Some('\u{2500}'), Some('\u{253C}'), Some('\u{00E3}'), Some('\u{00C3}'), // 0xC0
    Some('\u{255A}'), Some('\u{2554}'), Some('\u{2569}'), Some('\u{2566}'), Some('\u{2560}'), Some('\u{2550}'), Some('\u{256C}'), Some('\u{00A4}'), // 0xC8
    Some('\u{00F0}'), Some('\u{00D0}'), Some('\u{00CA}'), Some('\u{00CB}'), Some('\u{00C8}'), Some('\u{0131}'), Some('\u{00CD}'), Some('\u{00CE}'), // 0xD0
    Some('\u{00CF}'), Some('\u{2518}'), Some('\u{250C}'), Some('\u{2588}'), Some('\u{2584}'), Some('\u{00A6}'), Some('\u{00CC}'), Some('\u{2580}'), // 0xD8
    Some('\u{00D3}'), Some('\u{00DF}'), Some('\u{00D4}'), Some('\u{00D2}'), Some('\u{00F5}'), Some('\u{00D5}'), Some('\u{00B5}'), Some('\u{00FE}'), // 0xE0
    Some('\u{00DE}'), Some('\u{00DA}'), Some('\u{00DB}'), Some('\u{00D9}'), Some('\u{00FD}'), Some('\u{00DD}'), Some('\u{00AF}'), Some('\u{00B4}'), // 0xE8
    Some('\u{00AD}'), Some('\u{00B1}'), Some('\u{2017}'), Some('\u{00BE}'), Some('\u{00B6}'), Some('\u{00A7}'), Some('\u{00F7}'), Some('\u{00B8}'), // 0xF0
    Some('\u{00B0}'), Some('\u{00A8}'), Some('\u{00B7}'), Some('\u{00B9}'), Some('\u{00B3}'), Some('\u{00B2}'), Some('\u{25A0}'), Some('\u{00A0}'), // 0xF8
];
